# Generated by Django 4.2.16 on 2024-10-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('id_uc', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Gerador',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('id_uc', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
                ('endereco', models.CharField(max_length=30)),
            ],
        ),
    ]
