# Generated by Django 4.2.16 on 2024-10-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_consumidor_gerador'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ref', models.DateField()),
                ('dt_vcto', models.DateField()),
                ('id_client', models.IntegerField()),
                ('id_uc', models.IntegerField()),
                ('grandezas', models.CharField(max_length=100)),
                ('leitura_anterior', models.FloatField()),
                ('leitura_atual', models.FloatField()),
                ('const_medidor', models.FloatField()),
                ('consumo_kwh', models.FloatField()),
                ('qtd_enrg_tusd', models.FloatField()),
                ('prc_unit_tributos_tusd', models.FloatField()),
                ('tusd', models.FloatField()),
                ('pis_cofins_tusd', models.FloatField()),
                ('aliq_icms_tusd', models.FloatField()),
                ('icms_tusd', models.FloatField()),
                ('tarifa_unit_tusd', models.FloatField()),
                ('qtd_enrg_te', models.FloatField()),
                ('prc_unit_tributos_te', models.FloatField()),
                ('te', models.FloatField()),
                ('pis_cofins_te', models.FloatField()),
                ('aliq_icms_te', models.FloatField()),
                ('icms_te', models.FloatField()),
                ('tarifa_unit_te', models.FloatField()),
                ('qtd_enrg_compensada_tusd', models.FloatField()),
                ('prc_unit_tributos_compensada_tusd', models.FloatField()),
                ('compensada_tusd', models.FloatField()),
                ('pis_cofins_compensada_tusd', models.FloatField()),
                ('aliq_icms_compensada_tusd', models.FloatField()),
                ('icms_compensada_tusd', models.FloatField()),
                ('tarifa_unit_compensada_tusd', models.FloatField()),
                ('qtd_enrg_compensada_te', models.FloatField()),
                ('prc_unit_tributos_compensada_te', models.FloatField()),
                ('compensada_te', models.FloatField()),
                ('pis_cofins_compensada_te', models.FloatField()),
                ('aliq_icms_compensada_te', models.FloatField()),
                ('icms_compensada_te', models.FloatField()),
                ('tarifa_unit_compensada_te', models.FloatField()),
                ('multa', models.FloatField()),
                ('juros_mora', models.FloatField()),
                ('tx_2_emss_fat', models.FloatField()),
                ('dmic', models.FloatField()),
                ('pc_art113_ren414', models.FloatField()),
                ('cosip_cip', models.FloatField()),
                ('atualz_monetaria', models.FloatField()),
                ('rev_fat_atualiz', models.FloatField()),
                ('ren_1000', models.FloatField()),
                ('art_323', models.FloatField()),
                ('devol_pgto_fat_cancel', models.FloatField()),
                ('sem_corresp_saldo', models.FloatField()),
                ('cred_solu_rclm', models.FloatField()),
                ('cred_prox_fat', models.FloatField()),
                ('total', models.FloatField()),
                ('pis_cofins_total', models.FloatField()),
                ('icms_total', models.FloatField()),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='consumidor',
            name='id_uc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gerador',
            name='id_uc',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
