# Generated by Django 4.2.16 on 2024-10-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_leituracsv_alter_consumidor_id_uc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituracsv',
            name='qtd_enrg_compensada_te',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='qtd_enrg_compensada_tusd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
