# Generated by Django 4.2.16 on 2024-10-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_alter_leituracsv_qtd_enrg_compensada_te_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituracsv',
            name='cred_prox_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='prc_unit_tributos_compensada_te',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='prc_unit_tributos_compensada_tusd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
