# Generated by Django 4.2.16 on 2024-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_leituracsv_aliq_icms_compensada_te_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituracsv',
            name='art_323',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='atualz_monetaria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='devol_pgto_fat_cancel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='dmic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='pc_art113_ren414',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='ren_1000',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='rev_fat_atualiz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='sem_corresp_saldo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='tx_2_emss_fat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
