# Generated by Django 4.2.16 on 2024-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_leituracsv_juros_mora_alter_leituracsv_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituracsv',
            name='leitura_anterior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leituracsv',
            name='leitura_atual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
