# Generated by Django 4.2.16 on 2024-10-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_alter_leituracsv_leitura_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leituracsv',
            name='const_medidor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
