# Generated by Django 4.2.16 on 2024-10-27 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_alter_leituracsv_consumo_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 14, 44, 30, 617349)),
        ),
    ]
