# Generated by Django 4.2.16 on 2024-10-27 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_perfil_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumidor',
            name='id_client',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='consumidor',
            name='tipo',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='gerador',
            name='id_client',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='gerador',
            name='tipo',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 17, 35, 16, 391132)),
        ),
    ]
