# Generated by Django 4.2.16 on 2025-09-07 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galeria', '0013_consumidor_id_client_consumidor_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('data_associacao', models.DateField(auto_now_add=True)),
                ('unidade_geradora', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('gerador', 'Gerador'), ('consumidor', 'Consumidor'), ('misto', 'Misto')], max_length=10)),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateField()),
                ('total_geracao_distribuida_mw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_empreendimentos', models.IntegerField()),
                ('potencia_instalada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=2)),
                ('tipo_geracao', models.CharField(choices=[('solar', 'Solar'), ('eolica', 'Eólica'), ('hidro', 'Hidrelétrica')], max_length=20)),
                ('distribuidora', models.CharField(max_length=100)),
                ('fonte', models.CharField(default='ANEEL', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Micro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateField()),
                ('energia_gerada_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energia_consumida_kwh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_creditos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_compensacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referencia', models.DateField()),
                ('uc_geradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.cliente')),
            ],
            options={
                'unique_together': {('uc_geradora', 'mes_referencia')},
            },
        ),
        migrations.DeleteModel(
            name='Consumidor',
        ),
        migrations.DeleteModel(
            name='Gerador',
        ),
        migrations.DeleteModel(
            name='LeituraCSV',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
