# Generated by Django 4.2.16 on 2025-10-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0014_cliente_macro_micro_delete_consumidor_delete_gerador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMicro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ref', models.DateField()),
                ('dt_vcto', models.DateField()),
                ('id_client', models.IntegerField()),
                ('id_uc', models.IntegerField()),
                ('grandezas', models.CharField(max_length=100)),
                ('leitura_anterior', models.FloatField(blank=True, null=True)),
                ('leitura_atual', models.FloatField(blank=True, null=True)),
                ('const_medidor', models.FloatField(blank=True, null=True)),
                ('consumo_kwh', models.FloatField(blank=True, null=True)),
                ('prc_unit_tributos_tusd', models.FloatField(blank=True, null=True)),
                ('tarifa_unit_tusd', models.FloatField(blank=True, null=True)),
                ('prc_unit_tributos_te', models.FloatField(blank=True, null=True)),
                ('tarifa_unit_te', models.FloatField(blank=True, null=True)),
                ('qtd_enrg_compensada_tusd', models.FloatField(blank=True, null=True)),
                ('prc_unit_tributos_compensada_tusd', models.FloatField(blank=True, null=True)),
                ('tarifa_unit_compensada_tusd', models.FloatField(blank=True, null=True)),
                ('qtd_enrg_compensada_te', models.FloatField(blank=True, null=True)),
                ('prc_unit_tributos_compensada_te', models.FloatField(blank=True, null=True)),
                ('tarifa_unit_compensada_te', models.FloatField(blank=True, null=True)),
                ('cred_prox_fat', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('pis_cofins_total', models.FloatField(blank=True, null=True)),
                ('icms_total', models.FloatField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('tarifas', models.FloatField(blank=True, null=True)),
                ('solar', models.FloatField(blank=True, null=True)),
                ('impostos', models.FloatField(blank=True, null=True)),
                ('juros', models.FloatField(blank=True, null=True)),
                ('ress', models.FloatField(blank=True, null=True)),
                ('outros', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('gerador', 'Gerador'), ('consumidor', 'Consumidor'), ('prosumidor', 'Prosumidor')], max_length=10),
        ),
    ]
